config:
  info: main branch,springcloud/config-dev.yml version=7
  type: com.alibaba.druid.pool.DruidDataSource
  username: root
  password: 123
  dbUrl: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Hongkong
  driverClassName: com.mysql.cj.jdbc.Driver
